# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=150)),
                ('duration', models.CharField(choices=[('1', '2 Weeks'), ('2', '8 Weeks')], max_length=7)),
                ('image', models.ImageField(upload_to='', verbose_name='uploads/')),
            ],
        ),
    ]
